# Generated by Django 4.1.7 on 2023-03-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_task_assignees_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'default_related_name': 'tasks', 'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
