# Generated by Django 4.1.7 on 2023-04-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_task_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_date',
            field=models.DateTimeField(null=True),
        ),
    ]
