# Generated by Django 4.1.7 on 2023-04-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_task_complete_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete_date',
        ),
    ]
